kind: ConfigMap
apiVersion: v1
metadata:
  name: auditd-config
  namespace: openshift-logging
  labels:
    k8s-app: auditd-logging
data:
  auditd.conf: |
    #
    # NOTE: This file is managed by the auditd-config ConfigMap
    # ---
    # This file controls the configuration of the audit daemon
    #

    local_events = yes
    write_logs = yes
    log_file = /var/log/audit/audit.log
    log_group = root
    log_format = RAW
    flush = INCREMENTAL_ASYNC
    freq = 50
    max_log_file = 8
    num_logs = 5
    priority_boost = 4
    disp_qos = lossy
    dispatcher = /sbin/audispd
    name_format = NONE
    ##name = mydomain
    max_log_file_action = ROTATE
    space_left = 75
    space_left_action = SYSLOG
    verify_email = yes
    action_mail_acct = root
    admin_space_left = 50
    admin_space_left_action = SUSPEND
    disk_full_action = SUSPEND
    disk_error_action = SUSPEND
    use_libwrap = yes
    ##tcp_listen_port = 60
    tcp_listen_queue = 5
    tcp_max_per_addr = 1
    ##tcp_client_ports = 1024-65535
    tcp_client_max_idle = 0
    enable_krb5 = no
    krb5_principal = auditd
    ##krb5_key_file = /etc/audit/audit.key
    distribute_network = no

  auditd-stop.rules: |
    # NOTE: This file is managed by the auditd-config ConfigMap
    # ---
    # These rules are loaded when the audit daemon stops
    # if configured to do so.

    # Disable auditing
    -e 0

    # Delete all rules
    -D
  audit.rules: |
    # NOTE: This file is managed by the auditd-config ConfigMap
    # ---
    # This file contains the auditctl rules that are loaded
    # whenever the audit daemon is started via the initscripts.
    # The rules are simply the parameters that would be passed
    # to auditctl.

    # First rule - delete all
    -D

    # This suppresses syscall auditing for all tasks started
    # with this rule in effect.  Remove it if you need syscall
    # auditing.
    -a task,never
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: auditd
  namespace: openshift-logging
  labels:
    k8s-app: auditd-logging
spec:
  selector:
    matchLabels:
      name: auditd
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: auditd
    spec:
      initContainers:
      - name: init-audit-logs
        image: image-registry.openshift-image-registry.svc:5000/openshift/auditd:latest
        command: ['sh', '-c', 'mkdir -p /var/log/audit']
        volumeMounts:
        - mountPath: /var/log
          name: varlog
      containers:
      - name: auditd
        image: image-registry.openshift-image-registry.svc:5000/openshift/auditd:latest
        securityContext:
          privileged: true
          #capabilities:
          #  add: ["AUDIT_READ", "AUDIT_CONTROL", "AUDIT_WRITE", "SYS_NICE"]
          #seLinuxOptions:
          #  #user: system_u
          #  #role: system_r
          #  type: auditd_t
          #  #level: s0
        volumeMounts:
        - mountPath: /dev/log
          name: devlog
        - mountPath: /var/log/audit
          name: auditlog
        - mountPath: /etc/audit/
          name: auditdconfig
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      hostIPC: true
      schedulerName: default-scheduler
      serviceAccount: logcollector
      serviceAccountName: logcollector
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/log
          type: ""
        name: devlog
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/log/audit
          type: ""
        name: auditlog
      - name: auditdconfig
        configMap:
          name: auditd-config
          defaultMode: 0610
          items:
          - key: auditd.conf
            path: auditd.conf
          - key: auditd-stop.rules
            path: auditd-stop.rules
          - key: audit.rules
            path: rules.d/audit.rules
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
