apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: auditd
  namespace: openshift-logging
  labels:
    k8s-app: auditd-logging
spec:
  selector:
    matchLabels:
      name: auditd
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        name: auditd
    spec:
      initContainers:
      - name: init-audit-logs
        image: image-registry.openshift-image-registry.svc:5000/openshift-logging/auditd:latest
        command: ['sh', '-c', 'mkdir -p /var/log/audit']
        volumeMounts:
        - mountPath: /var/log
          name: varlog
      containers:
      - name: auditd
        image: image-registry.openshift-image-registry.svc:5000/openshift-logging/auditd:latest
        securityContext:
          privileged: true
          #capabilities:
          #  add: ["AUDIT_READ", "AUDIT_CONTROL", "AUDIT_WRITE", "SYS_NICE"]
          #seLinuxOptions:
          #  #user: system_u
          #  #role: system_r
          #  type: auditd_t
          #  #level: s0
        volumeMounts:
        - mountPath: /dev/log
          name: devlog
        - mountPath: /var/log
          name: varlog
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      schedulerName: default-scheduler
      serviceAccount: logcollector
      serviceAccountName: logcollector
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/log
          type: ""
        name: devlog
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
